### PR TITLE
Demo 4

### PR DESCRIPTION
**Pull request by michaelrosstarr**

### CODE REVIEW

**Review by Inge505 — APPROVED** [review]
LGTM

**Comment by michaelrosstarr** [comment]
> #### ⚠️ GitGuardian has uncovered 14 secrets following the scan of your pull request.
> Please consider investigating the findings and remediating the incidents. Failure to do so may lead to compromising the associated services or software components.
> 
> 🔎 Detected hardcoded secrets in your pull request
> 
> GitGuardian id	Secret	Commit	Filename	
> [7540202](https://dashboard.gitguardian.com/incidents/7540202?occurrence=115602701)	Generic High Entropy Secret	[b76152d](https://github.com/COS301-SE-2023/Avalanche/commit/b76152d812672aedab7efca1a74c5f53fe39fa87)	gateway/src/user-management/user-management-integration.service.spec.ts	[View secret](https://github.com/COS301-SE-2023/Avalanche/commit/b76152d812672aedab7efca1a74c5f53fe39fa87#diff-378b80a528a1f71ac1ea27b626fb8faf1185973c846d1ae92a7f2037c6d6e26eL57)
> [7540202](https://dashboard.gitguardian.com/incidents/7540202?occurrence=115605464)	Generic High Entropy Secret	[934cad5](https://github.com/COS301-SE-2023/Avalanche/commit/934cad54692b586c71e460dd57c2b5f8bc970139)	gateway/src/user-management/user-management-integration.service.spec.ts	[View secret](https://github.com/COS301-SE-2023/Avalanche/commit/934cad54692b586c71e460dd57c2b5f8bc970139#diff-378b80a528a1f71ac1ea27b626fb8faf1185973c846d1ae92a7f2037c6d6e26eL57)
> [7540202](https://dashboard.gitguardian.com/incidents/7540202?occurrence=115747439)	Generic High Entropy Secret	[cb78847](https://github.com/COS301-SE-2023/Avalanche/commit/cb788476fffd9562f07102b5025583c8a31283e6)	gateway/src/user-management/user-management-integration.service.spec.ts	[View secret](https://github.com/COS301-SE-2023/Avalanche/commit/cb788476fffd9562f07102b5025583c8a31283e6#diff-378b80a528a1f71ac1ea27b626fb8faf1185973c846d1ae92a7f2037c6d6e26eL57)
> [7540202](https://dashboard.gitguardian.com/incidents/7540202?occurrence=115754544)	Generic High Entropy Secret	[6cf4391](https://github.com/COS301-SE-2023/Avalanche/commit/6cf43913a14583cc57b24774dfb5605c2c1c22bc)	gateway/src/user-management/user-management-integration.service.spec.ts	[View secret](https://github.com/COS301-SE-2023/Avalanche/commit/6cf43913a14583cc57b24774dfb5605c2c1c22bc#diff-378b80a528a1f71ac1ea27b626fb8faf1185973c846d1ae92a7f2037c6d6e26eL57)
> [7540202](https://dashboard.gitguardian.com/incidents/7540202?occurrence=115816046)	Generic High Entropy Secret	[4846c32](https://github.com/COS301-SE-2023/Avalanche/commit/4846c329ed990dc947562c5391b261a5fed1e476)	gateway/src/user-management/user-management-integration.service.spec.ts	[View secret](https://github.com/COS301-SE-2023/Avalanche/commit/4846c329ed990dc947562c5391b261a5fed1e476#diff-378b80a528a1f71ac1ea27b626fb8faf1185973c846d1ae92a7f2037c6d6e26eL57)
> [8065000](https://dashboard.gitguardian.com/incidents/8065000?occurrence=115868132)	SMTP credentials	[369a913](https://github.com/COS301-SE-2023/Avalanche/commit/369a9136aa4626ec0eb75fcaaf52339d9b8446d1)	gateway/src/domain-watch/domain-watch.service.ts	[View secret](https://github.com/COS301-SE-2023/Avalanche/commit/369a9136aa4626ec0eb75fcaaf52339d9b8446d1#diff-b1e2b29701e9e4a8813c95ab416a6846946e9b30942aba046dd6ee446d8809c7L77)
> [8065000](https://dashboard.gitguardian.com/incidents/8065000?occurrence=115868228)	SMTP credentials	[12ab62a](https://github.com/COS301-SE-2023/Avalanche/commit/12ab62a0d59b0501626aa6de12b640003666871e)	gateway/src/domain-watch/domain-watch.service.ts	[View secret](https://github.com/COS301-SE-2023/Avalanche/commit/12ab62a0d59b0501626aa6de12b640003666871e#diff-b1e2b29701e9e4a8813c95ab416a6846946e9b30942aba046dd6ee446d8809c7L77)
> [8065000](https://dashboard.gitguardian.com/incidents/8065000?occurrence=115868464)	SMTP credentials	[050f7ef](https://github.com/COS301-SE-2023/Avalanche/commit/050f7ef40c7771f9ddfb4038a2f23f7cfb807053)	gateway/src/domain-watch/domain-watch.service.ts	[View secret](https://github.com/COS301-SE-2023/Avalanche/commit/050f7ef40c7771f9ddfb4038a2f23f7cfb807053#diff-b1e2b29701e9e4a8813c95ab416a6846946e9b30942aba046dd6ee446d8809c7L79)
> [8206301](https://dashboard.gitguardian.com/incidents/8206301?occurrence=115602700)	Generic High Entropy Secret	[b76152d](https://github.com/COS301-SE-2023/Avalanche/commit/b76152d812672aedab7efca1a74c5f53fe39fa87)	gateway/src/user-management/user-management-integration.service.spec.ts	[View secret](https://github.com/COS301-SE-2023/Avalanche/commit/b76152d812672aedab7efca1a74c5f53fe39fa87#diff-378b80a528a1f71ac1ea27b626fb8faf1185973c846d1ae92a7f2037c6d6e26eR14)
> [8206301](https://dashboard.gitguardian.com/incidents/8206301?occurrence=115605463)	Generic High Entropy Secret	[934cad5](https://github.com/COS301-SE-2023/Avalanche/commit/934cad54692b586c71e460dd57c2b5f8bc970139)	gateway/src/user-management/user-management-integration.service.spec.ts	[View secret](https://github.com/COS301-SE-2023/Avalanche/commit/934cad54692b586c71e460dd57c2b5f8bc970139#diff-378b80a528a1f71ac1ea27b626fb8faf1185973c846d1ae92a7f2037c6d6e26eR14)
> [8206301](https://dashboard.gitguardian.com/incidents/8206301?occurrence=115747440)	Generic High Entropy Secret	[cb78847](https://github.com/COS301-SE-2023/Avalanche/commit/cb788476fffd9562f07102b5025583c8a31283e6)	gateway/src/user-management/user-management-integration.service.spec.ts	[View secret](https://github.com/COS301-SE-2023/Avalanche/commit/cb788476fffd9562f07102b5025583c8a31283e6#diff-378b80a528a1f71ac1ea27b626fb8faf1185973c846d1ae92a7f2037c6d6e26eR14)
> [8206301](https://dashboard.gitguardian.com/incidents/8206301?occurrence=115754205)	Generic High Entropy Secret	[5d6faef](https://github.com/COS301-SE-2023/Avalanche/commit/5d6faeffc01ed1df9823c51250422a5f121c9f37)	gateway/src/user-management/user-management-integration.service.spec.ts	[View secret](https://github.com/COS301-SE-2023/Avalanche/commit/5d6faeffc01ed1df9823c51250422a5f121c9f37#diff-378b80a528a1f71ac1ea27b626fb8faf1185973c846d1ae92a7f2037c6d6e26eL14)
> [8206301](https://dashboard.gitguardian.com/incidents/8206301?occurrence=115825342)	Generic High Entropy Secret	[0d98c23](https://github.com/COS301-SE-2023/Avalanche/commit/0d98c237e4b2654714c17051d678b02b516d09e7)	gateway/src/user-management/user-management-integration.service.spec.ts	[View secret](https://github.com/COS301-SE-2023/Avalanche/commit/0d98c237e4b2654714c17051d678b02b516d09e7#diff-378b80a528a1f71ac1ea27b626fb8faf1185973c846d1ae92a7f2037c6d6e26eL14)
> [8206301](https://dashboard.gitguardian.com/incidents/8206301?occurrence=115825417)	Generic High Entropy Secret	[3ac0658](https://github.com/COS301-SE-2023/Avalanche/commit/3ac0658f43f0ee951f3a19934dc2f94a4e2eaad7)	gateway/src/user-management/user-management-integration.service.spec.ts	[View secret](https://github.com/COS301-SE-2023/Avalanche/commit/3ac0658f43f0ee951f3a19934dc2f94a4e2eaad7#diff-378b80a528a1f71ac1ea27b626fb8faf1185973c846d1ae92a7f2037c6d6e26eL14)
> 🛠 Guidelines to remediate hardcoded secrets
> 🦉 [GitGuardian](https://dashboard.gitguardian.com/auth/login/?utm_medium=checkruns&utm_source=github&utm_campaign=cr1) detects secrets in your source code to help developers and security teams secure the modern development process. You are seeing this because you or someone else with access to this repository has authorized GitGuardian to scan your pull request.Our GitHub checks need improvements? [Share your feedbacks](https://050127dayho.typeform.com/to/KmeAPTMk)!

these are old, we have removed them, rerolled them

**Review by markbr02 — APPROVED** [review]
finally

**Review by GT-GillesTeuwen — APPROVED** [review]
Saw it working
Not gonna look through 2 million lines 

I trust you Mikey 

Don't let me down

**Pull request merged**
